# Generated by Django 5.2 on 2025-05-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_alter_journal_journal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='journal_image',
        ),
    ]
