# Generated by Django 5.2 on 2025-05-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_remove_journal_journal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_images/'),
        ),
    ]
