# Generated by Django 5.2 on 2025-05-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0011_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
