# Generated by Django 5.2 on 2025-05-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0012_profile_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='goal',
            new_name='career_goal',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_goals',
            field=models.CharField(blank=True),
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
