# Generated by Django 5.2 on 2025-05-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0013_remove_userselection_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
